@host = https://jjvlkr6woj.execute-api.us-east-1.amazonaws.com

###
GET  {{host}}/products

###
GET  {{host}}/products/0ff5dce8-3a05-430f-8b76-967252965d0b

###
POST  {{host}}/products
Content-Type: application/json

{
  "name": "Camiseta NodeJS",
  "price": 129.99,
  "tags": ["backend", "runtime"]
}
###
PUT  {{host}}/products/{productId}

###
DELETE  {{host}}/products/0ff5dce8-3a05-430f-8b76-967252965d0b